services/django/book/urls.py
from django.conf.urls import url
#from django.urls import  path

from book import views

app_name = 'book'
urlpatterns = [
    url(r'^$',                     views.BookList.as_view()),
    url(r'^publishers',            views.PublisherList.as_view(),  name='publisher_list'),
    url(r'^books',                 views.books_list,               name='books_list'),
    url(r'^books/(\d+)$',          views.book_detail,              name='book_detail'),
    url(r'^books/reader/(\d+)$',   views.book_read,                name='book_read'),
]

services/django/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from homepages import views as home_view

urlpatterns = [
    url(r'^mysite/admin/', admin.site.urls),
    path('mysite/about/', TemplateView.as_view(template_name="homepages/about.html"), name="about"),
    url(r'^mysite/pages/', include('homepages.urls')),
    # url(r'^mysite/books/', include('book.urls')),
    url(r'^mysite/lists/', include('lists.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/django/book/models.py
from django.db import models
from django.template.defaultfilters import default
from django.conf import  settings
#from django_pandas.managers import DataFrameManager

# Create your models here.

class Classfication(models.Model):
    pass


class Author(models.Model):
    first_name = models.CharField('名', max_length=30)
    last_name = models.CharField('姓氏', max_length=40)
    email = models.EmailField('邮箱', blank=True)
    pseudonym = models.CharField('笔名', max_length=30, blank=True)
    headshot = models.ImageField('相片', upload_to='author_headshots', blank=True, null=True)
    sex = models.BooleanField(max_length=1, choices=((0, '男'), (1, '女'),),default=0)

    def __str__(self):
        if self.pseudonym:
            return u'%s %s  (笔名：%s)' % (self.first_name, self.last_name, self.pseudonym)
        else:
            return u'%s %s' % (self.first_name, self.last_name)

    # 对于使用Django自带的通用视图非常重要
    # def get_absolute_url(self):
    #     # return reverse('pic_upload:pic_detail', args=[str(self.id)])
    #     return (settings.MEDIA_URL+'author_headshots/'+str(self.id)+'.png')

    class Meta:
        ordering = ['last_name']


class Publisher(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=50, blank=True)
    state_province = models.CharField(max_length=20, blank=True)
    country = models.CharField(max_length=50, blank=True)
    website = models.URLField(blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


def file_dir_path(instance, filename=None):
    # file will be uploaded to MEDIA_ROOT/books/<book.id>.txt
    return 'books/{0}.txt'.format(instance.id)


class Book(models.Model):
    title = models.CharField('书名', max_length=100)
    book_cover = models.ImageField('封面', upload_to='books', blank=True, null=True)
    authors = models.ManyToManyField(Author)
    classfication = models.ForeignKey(Classfication, on_delete=models.SET_NULL, null=True,  blank=True)
    publisher = models.ForeignKey(Publisher, on_delete=models.SET_NULL, null=True, blank=True)
    publication_date = models.DateField(blank=True, null=True)
    filepath = models.FileField(upload_to=file_dir_path, null=True)
    abstract = models.CharField('摘要', max_length= 300, null=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']


# class Securities(models.Model):
#     code = models.CharField(max_length=16)
#     name = models.CharField(max_length=30)
#
#     def __str__(self):
#         return self.code
#
#
# class TransactionData_Day(models.Model):
#     code = models.ForeignKey(Securities)
#     date = models.DateField()
#     open = models.FloatField()
#     close = models.FloatField()
#     high = models.FloatField()
#     low = models.FloatField()
#     volume = models.FloatField()
#     adjclose = models.FloatField(default=0)
# #     ma5 = models.FloatField()
# #     v_ma5 = models.FloatField()
# #     ma10 = models.FloatField()
# #     v_ma10 = models.FloatField()
# #     ma20 = models.FloatField()
# #     v_ma20 = models.FloatField()
#
#     objects = DataFrameManager()
#
#     def __str__(self):
#         return u'%s %s' % (self.code, self.date)
#
#     class Meta:
#         ordering = ['date']

services/django/book/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView

from django.conf import settings

import  os
import re

from book.models import Publisher, Author, Book, file_dir_path

# Create your views here.


class PublisherList(ListView):

    model = Publisher
    context_object_name = '出版商'


class PublisherDetail(DetailView):

    model = Publisher

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['book_list'] = Book.objects.all()
        return context


class PublisherBookList(ListView):

    template_name = 'book/books_by_publisher.html'

    def get_queryset(self):
        self.publisher = get_object_or_404(Publisher, name=self.kwargs['publisher'])
        return Book.objects.filter(publisher=self.publisher)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in the publisher
        context['publisher'] = self.publisher
        return context


class BookList(ListView):
    queryset = Book.objects.order_by('publication_date')
    context_object_name = 'book_list'


def books_list(request):
    books = Book.objects.order_by('publication_date')
    for book in books:
        authors = Author.objects.filter(book__id=book.id)
        book.author_name_list = ','.join(str(author) for author in authors)
    return render(request, 'book/book_list.html', {'object_list': books,
                                                   'directory': True})


def book_detail(request, id):
    book = get_object_or_404(Book, pk=id)
    authors = Author.objects.filter(book__id=id)
    book.author_name_list = ','.join(str(author) for author in authors)

    filepath = file_dir_path(book)
    file = os.path.join(settings.MEDIA_ROOT, filepath.replace('/', '\\'))

    with open(str(file), encoding='utf-16') as f:
        titles = []
        title = None

        regEx = r"第[\u4E00-\u9FA5]+章";
        pattern = re.compile(regEx)

        for line in f:
            if pattern.match(line):
                titles.append(line.strip())

    return render(request, 'book/book_detail.html', {'book': book, 'titles': titles, 'sidebar': True})


def book_read(request, id):
    line_per_page = 150              #每页显示的行数

    book = get_object_or_404(Book, pk=id)
    authors = Author.objects.filter(book__id=id)
    book.author_name_list = ','.join(str(author) for author in authors)

    filepath = file_dir_path(book)
    file = os.path.join(settings.MEDIA_ROOT, filepath.replace('/', '\\'))

    with open(str(file), encoding='utf-16') as f:
        contents = []
        title = None

        regEx = r"第[\u4E00-\u9FA5]+章";
        pattern = re.compile(regEx)

        for line in f:
            if pattern.match(line):
                if not title:
                    title = line[:]
                    continue
                else:
                    break
            else:
                contents.append(line.strip())
    return render(request, 'book/book_read.html', {'book': book, 'title': title, 'contents': contents})

services/django/templates/book/book_detail.html
{% extends "base.html" %}

{% block title %}Web Application{% endblock %}

{% block header_text %}
        {% if book.book_cover %}
            <img src="{{ book.book_cover.url }}" alt="headshot" width="105" height="142"/>
        {% endif %}
        <h3>
            书名： {{ book.title }} </a>
        </h3>
        <h3>
            作者: {{ book.author_name_list }}
{#                {% for author in authors %}#}
{#                        {{ author }}#}
{#                        {% if author.headshot %}#}
{#                            <img src="{{ author.headshot.url }}" alt="headshot" height="142"/>#}
{#                        {% endif %}#}
{#                {% endfor %}#}
        </h3>
        <h3>出版商: {{ book.publisher }}</h3>
        <h3>出版日期: {{ book.publication_date }}</h3>

{% endblock %}


{% block sidebar_content %}
    <h2>简介：</h2>
    <p>
        {{ book.abstract }}
    </p>
{% endblock %}

{% block content %}
        <h1>
            <a href={% url 'book:book_read' book.id %}>
            {{ book.title }}
            </a>
        </h1>
        <hr>
        {% for title in titles %}
            <p>
                {{ title }}
            </p>
        {% endfor %}

{% endblock %}

services/django/templates/book/book_list.html
{% extends "base.html" %}

{% block title %}Web Application{% endblock %}

{% block header_text %}
		<img id="headerLogo" src="/static/images/svg_logo.svg" alt="logo" width="100" height="100" />
        <h1 class="slogan">Welcome to Xu Zhiyong's</h1>
        <h1 class="slogan">Book Management System!</h1>
{% endblock %}

{% block sidebar %}
    <p> 图书内容的简介 </p>
{% endblock %}

{% block directory %}
    <ul>
        <li>通用技术类</li>
        <li>计算机软件类</li>
        <li>人工智能</li>
        <li>视频图像</li>
        <li>小说</li>
    </ul>
{% endblock %}

{% block content %}
    <table>
        <caption>书目清单</caption>
        <thead>
            <tr>
                <th>书名</th>
                <th>作者</th>
                <th>出版商</th>
                <th>出版日期</th>
            </tr>
        </thead>
        <tbody>
            {% for book in object_list %}
                <tr>
                    <td>
                        <a href={% url 'book:book_detail' book.id %}>
                            {{ book.title }}
                        </a>
                    </td>
                    <td>
                           {{ book.author_name_list}}
                    </td>
                    <td>
                        {{ book.publisher }}
                    </td>
                    <td>
                        {{ book.publication_date }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

services/django/templates/book/book_read.html
{% extends "base.html" %}

{% block title %}Web Application{% endblock %}

{% block header_text %}
    <div id="page_set">
            <li style="position: relative; float: right; width:460px">
                <select name="bgcolor" class="stylectl" id="bgcolor">
                    <option style="background-color: #e3e8f7" value="#f6f6f6">底色</option>
                    <option style="background-color: #f6f6f6" value="#f6f6f6">半灰</option>
                    <option style="background-color: #ffffff" value="#ffffff">白色</option>
                    <option style="background-color: #e3e8f7" value="#e3e8f7">淡蓝</option>
                    <option style="background-color: #daebfc" value="#daebfc">蓝色</option>
                    <option style="background-color: #ebeaea" value="#ebeaea">淡灰</option>
                    <option style="background-color: #e7e3e6" value="#e7e3e6">灰色</option>
                    <option style="background-color: #dedcd8" value="#dedcd8">深灰</option>
                    <option style="background-color: #d8d7d7" value="#d8d7d7">暗灰</option>
                    <option style="background-color: #e6fae4" value="#e6fae4">绿色</option>
                    <option style="background-color: #f9fbdd" value="#f9fbdd">明黄</option>
                </select>
                <select name="fontcolor" class="stylectl" id="fontcolor">
                    <option value="#000000">字色</option>
                    <option value="#000000">黑色</option>
                    <option value="#a10d0d">红色</option>
                    <option value="#167b0b">绿色</option>
                    <option value="#0d3475">蓝色</option>
                    <option value="#660000">棕色</option>
                </select>
                <select name="fontsize" class="stylectl" id="fontsize">
                    <option value="16px">字号</option>
                    <option value="14px">小号</option>
                    <option value="16px">较小</option>
                    <option value="18px">中号</option>
                    <option value="20px">较大</option>
                    <option value="24px">大号</option>
                    <option value="28px">特大</option>
                </select>
                <select name="fontfamily" class="stylectl" id="fontfamily">
                    <option value="宋体">字体</option>
                    <option value="宋体">宋体</option>
                    <option value="微软雅黑">微软雅黑</option>
                    <option value="黑体">黑体</option>
                    <option value="楷书">楷体</option>
                    <option value="隶书">隶书</option>
                </select>
                <select name="divwidth" class="stylectl" id="divwidth">
                    <option value="80%">宽度</option>
                    <option value="50%">50%</option>
                    <option value="60%">60%</option>
                    <option value="70%">70%</option>
                    <option value="80%">80%</option>
                    <option value="90%">90%</option>
                    <option value="100%">100%</option>
                </select>
                <select name="divsudu" class="stylectl" id="divsudu" style="">
                    <option value="50">双击滚屏</option>
                    <option value="800">1</option>
                    <option value="500">2</option>
                    <option value="200">3</option>
                    <option value="100">4</option>
                    <option value="80">5</option>
                    <option value="50">6</option>
                    <option value="30">7</option>
                    <option value="10">8</option>
                    <option value="5">9</option>
                    <option value="3">10</option>
                </select>
            </li>
    </div>

    {% if book.book_cover %}
        <img src="{{ book.book_cover.url }}" alt="headshot" width="105" height="142">
    {% endif %}

    <h3>书名： {{ book.title }}  </h3>
    <h3>作者: {{ book.author_name_list }}  </h3>
    <h3>出版商: {{ book.publisher }}</h3>
    <h3>出版日期: {{ book.publication_date }}</h3>
{% endblock %}

{% block content %}
    <ul id="listTitle">
        <li class="selected"><a href={% url 'book:book_read' book.id%}>第一章</a></li>
        <li><a href={% url 'book:book_read' book.id%}>第二章</a></li>
        <li><a href={% url 'book:book_read' book.id%}>第三章</a></li>
    </ul>

    <article>
        <header>
            <h2>{{ title }}</h2>
            <time datetime="2016-12-01">2018-11-11</time>
        </header>

        {% for content in contents %}
            <p>
                {{ content }}
            </p>
        {% endfor %}
    </article>
{% endblock %}

services/django/templates/book/book_summary.html
{% extends 'base.html' %}

{% block title %}Web Application{% endblock %}

{% block header_text %}
    <img src="/static/images/svg_logo.svg" alt="logo" width="100" height="100" />
    <h1 class="slogan">Welcome to Xu Zhiyong's Home Page!</h1>
{% endblock %}

{% block content %}
    <h2>
        Book ID is:
    </h2>
    <p class="text-center"> {{ novel_id }}</p>
{% endblock %}

services/django/templates/book/books_by_publisher.html
{% extends "base.html" %}

{% block title %}Web Application{% endblock %}

{% block content %}
    <h1>
		<img src="/static/images/svg_logo.svg" alt="logo" width="100" height="100" />
		Welcome to Xu Zhiyong's Novel System!
	</h1>

    <br>
    <h2>Publishers</h2>
    <ul>
        {% for publisher in object_list %}
            <li>{{ publisher.name }}</li>
        {% endfor %}
    </ul>
{% endblock %}

services/django/templates/book/publisher_list.html
{% extends "base.html" %}

{% block title %}Web Application{% endblock %}

{% block content %}
    <h1>
		<img src="/static/images/svg_logo.svg" alt="logo" width="100" height="100" />
		Welcome to Xu Zhiyong's Novel System!
	</h1>

    <br>
    <h2>Publishers</h2>
    <ul>
        {% for publisher in object_list %}
            <li>{{ publisher.name }}</li>
        {% endfor %}
    </ul>
{% endblock %}