services/django/book/urls.py
from django.conf.urls import url
#from django.urls import  path

from book import views

app_name = 'book'
urlpatterns = [
    url(r'^$',                     views.BookList.as_view()),
    url(r'^publishers',            views.PublisherList.as_view(),  name='publisher_list'),
    url(r'^books',                 views.books_list,               name='books_list'),
    url(r'^books/(\d+)$',          views.book_detail,              name='book_detail'),
    url(r'^books/reader/(\d+)$',   views.book_read,                name='book_read'),
]

services/django/lists/urls.py
from django.conf.urls import url
from lists import views

app_name = 'lists'
urlpatterns = [
    url(r'^$',               views.lists_homepage,  name='home'),
    # url(r'^the-only-list-in-the-world/$',
    #                          views.view_list,       name='view_list'),
    url(r'^(\d+)/$',         views.view_list,       name='view_list'),
    url(r'^new$',            views.new_list,        name='new_list'),
]

services/django/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from homepages import views as home_view

urlpatterns = [
    url(r'^mysite/admin/', admin.site.urls),
    path('mysite/about/', TemplateView.as_view(template_name="homepages/about.html"), name="about"),
    url(r'^mysite/pages/', include('homepages.urls')),
    # url(r'^mysite/books/', include('book.urls')),
    url(r'^mysite/lists/', include('lists.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/django/lists/models.py
from django.db import models
# from django.template.defaultfilters import default
# from django.urls import reverse

# Create your models here.


class List(models.Model):
    name = models.CharField(max_length=30, default='')

    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

    def __str__(self):
        return self.name


class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None, on_delete=models.PROTECT)

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

    def __str__(self):
        return self.text

services/django/lists/forms.py
from django import forms
from django.core.exceptions import ValidationError

from lists.models import Item


# class ItemForm(forms.Form):
#
#     text = forms.CharField(
#         widget=forms.fields.TextInput(attrs={
#             'placeholder': 'Enter a to-do item',
#             'class': 'form-control input-lg',
#         })
#     }
EMPTY_LIST_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"


class ItemForm(forms.models.ModelForm):

    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(
                attrs={
                    'placeholder': 'Enter a to-do item',
                    'class': 'form-control input-lg',
                }),
        }
        error_messages = {
            'text': {'required': EMPTY_LIST_ERROR}
        }

    def save(self, for_list):
        self.instance.list = for_list
        return super().save()


class ExistingListItemForm(ItemForm):

    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

    def save(self):
        return forms.models.ModelForm.save(self)

services/django/lists/views.py
from django.shortcuts import render, redirect
from django.http import  HttpResponse
from django.core.exceptions import ValidationError

import datetime

# Create your views here.
from lists.models import Item, List
# from lists.forms import ItemForm, ExistingListItemForm


def lists_homepage(request):
    """
    # R1:
    return render(request, 'lists/home.html')

    # R1.1:
    return render(request, 'lists/home.html',
                  {'new_item_text': request.POST.get('item_text', '')})

    # R1.2:
    item = Item()
    item.text = request.POST.get('item_text', '')
    item.save()

    return render(request, 'lists/home.html',
                  {'new_item_text': item.text})

    # R1.3:
    if request.method == 'POST':
        new_item_text = request.POST['item_text']
        Item.objects.create(text=new_item_text)
    else:
        new_item_text = ''
    return render(request, 'lists/home.html',
                  {'new_item_text': new_item_text})

    # R1.4:
    if request.method == 'POST':
        Item.objects.create(text=request.POST['item_text'])
        return redirect('/')
    else:
        return render(request, 'lists/home.html')

    # R1.5:
    if request.method == 'POST':
        Item.objects.create(text=request.POST['item_text'])
        return redirect('/lists/the-only-list-in-the-world/')
    else:
        items = Item.objects.all()
        return render(request, 'lists/home.html', {'items': items})

    # R1.6:
    if request.method == 'POST':
        Item.objects.create(text=request.POST['item_text'])
        return redirect('/lists/the-only-list-in-the-world/')
    else:
        return render(request, 'lists/home.html')
    """
    # R2 migrates POST to new_list view
    return render(request, 'lists/home.html')

    # R3: migrates POST to new_list view,
    #     via home.html: <form method="POST" action="lists/new">
    # return render(request, 'home.html', {'form': ItemForm()})


# Refactor due to introduce Item.list
# def view_list(request):
#     items = Item.objects.all()
#     return render(request, 'lists/list.html', {'items': items})

# Refactor in 6.9, in order to deal with POST request
# def view_list(request, list_id):
#     list_ = List.objects.get(id=list_id)
#     items = Item.objects.filter(list=list_)
#     return render(request, 'lists/list.html', {'items': items})

def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    items = Item.objects.filter(list=list_)

    error = None

    if request.method == 'POST':
        try:
            item = Item(text=request.POST['item_text'], list=list_)
            item.full_clean()
            item.save()
            return redirect('/mysite/lists/%d/' % (list_.id,))
        except ValidationError:
            error = "You can't have an empty list item"

    # Refactor to introduce {{list}} into template list.html
    # return render(request, 'lists/list.html', {'items': items})
    return render(request, 'lists/list.html', {'list': list_})

# return render(request, 'list.html', {'form': ItemForm(), 'list': list_,
# 'error': error})

# def view_list(request, list_id):
#     list_ = List.objects.get(id=list_id)
#     form = ExistingListItemForm(for_list=list_)
#     if request.method == 'POST':
#         form = ExistingListItemForm(for_list=list_, data=request.POST)
#         if form.is_valid():
#             #item = Item.objects.create(text=request.POST['text'], list=list_)
#             form.save()
#             return redirect(list_)
#     return render(request, 'list.html', {'form': form, 'list': list_, })


def new_list(request):
    # Refactor due to introduce Item.list
    # Item.objects.create(text=request.POST['item_text'])
    # return redirect('/lists/the-only-list-in-the-world/')

    list_ = List.objects.create()
    # Correct the bug here: item will be saved even it's empty
    # item = Item.objects.create(text=request.POST['item_text'], list=list_)
    item = Item(text=request.POST['item_text'], list=list_)
    try:
        item.full_clean()
        item.save()
    except ValidationError:
        list_.delete()
        error = "You can't have an empty list item"
        return render(request, 'lists/home.html', {"error": error})
    return redirect('/mysite/lists/%d/' % list_.id)

#     form = ItemForm(data=request.POST)
#     if form.is_valid():
#         list_ = List.objects.create()
#         #Item.objects.create(text=request.POST['text'], list=list_)
#         form.save(for_list=list_)
#         return redirect(list_)
#     else:
#         return render(request, 'home.html', {'form': form})

services/django/templates/lists/home.html
{% extends 'base.html' %}

{% block css %}
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link type="text/css" rel="stylesheet" href="/static/lists.css">
{% endblock %}

{% block title %}To-Do Lists{% endblock %}

{% block header_text %}
    <img id="headerLogo" src="/static/images/svg_logo.svg" alt="logo" width="100" height="100" />
    <h1 class="slogan"> Start a new To-Do list</h1>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3" jumbotron>
                <div class="text-center">
                    <form method="POST" action={% url 'lists:new_list' %} >
                        <label for="id_new_item"> Enter a To-Do Item: </label>
                        <input type="text" name="item_text" id="id_new_item"
                                    class="form-control input-lg" placeholder="Enter a to-do item"/>
                        {% csrf_token %}
                        {% if error %}
                          <div class="form-group has-error">
                            <span class="help-block">{{ error }}</span>
                          </div>
                        {% endif %}
                    </form>
                </div>
            </div> <!-- col-md-6 -->
        <div> <!-- row -->
    </div> <!-- container -->
{% endblock %}

{% block js %}
    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
{% endblock %}

services/django/templates/lists/list.html
{% extends 'base.html' %}

{% block css %}
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link type="text/css" rel="stylesheet" href="/static/lists.css">
{% endblock %}

{% block title %}Your To-Do list{% endblock %}

{% block header_text %}
    <img id="headerLogo" src="/static/images/svg_logo.svg" alt="logo" width="100" height="100" />
    <h1 class="slogan"> Your To-Do list</h1>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
          <div class="col-md-6 col-md-offset-3" jumbotron>
            <div class="text-center">
                <form method="POST" action="/lists/{{ list.id }}/" %} >
                    <label for="id_new_item"> Enter a To-Do Item: </label>
                    <input type="text" name="item_text" id="id_new_item"
                           class="form-control input-lg" placeholder="Enter a to-do item"/>
                    {% csrf_token %}
                    {% if error %}
                      <div class="form-group has-error">
                        <span class="help-block">{{ error }}</span>
                      </div>
                    {% endif %}
                </form>
            </div> <!-- text-center -->
          </div> <!-- col-md-6 -->
        <div> <!-- row -->

        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <table id="id_list_table" class="table">
                {% for item in list.item_set.all %}
                    <tr><td>{{ forloop.counter }}:{{ item.text }}</td></tr>
                {% endfor %}
            </table>
          </div> <!-- col-md-6 -->
        <div> <!-- row -->
    </div> <!-- container -->
{% endblock %}


{% block js %}
    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
{% endblock %}