services/django/book/urls.py
from django.conf.urls import url
#from django.urls import  path

from book import views

app_name = 'book'
urlpatterns = [
    url(r'^$',                     views.BookList.as_view()),
    url(r'^publishers',            views.PublisherList.as_view(),  name='publisher_list'),
    url(r'^books',                 views.books_list,               name='books_list'),
    url(r'^books/(\d+)$',          views.book_detail,              name='book_detail'),
    url(r'^books/reader/(\d+)$',   views.book_read,                name='book_read'),
]

services/django/homepages/urls.py
from django.conf.urls import url
from homepages import views

app_name = 'homepages'
urlpatterns = [
    url(r'^$',                     views.home_page,   name='home'),
    url(r'^datetime$',             views.date_time,   name='datetime'),
    url(r'^firstLoughe',           views.firstLoughe, name='firstLoughe'),
    url(r'^newLounge',             views.newLounge,   name='newLounge'),
    # url(r'^myFirstJavaScript',  views.myFirstJavaScript,  name='myFirstJavaScript'),
    # url(r'^json',                    views.json,             name='json'),
    # # url(r'^webui',                  webui.draw_picture, name='show_picture'),
]

services/django/lists/urls.py
from django.conf.urls import url
from lists import views

app_name = 'lists'
urlpatterns = [
    url(r'^$',               views.lists_homepage,  name='home'),
    # url(r'^the-only-list-in-the-world/$',
    #                          views.view_list,       name='view_list'),
    url(r'^(\d+)/$',         views.view_list,       name='view_list'),
    url(r'^new$',            views.new_list,        name='new_list'),
]

services/django/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from homepages import views as home_view

urlpatterns = [
    url(r'^mysite/admin/', admin.site.urls),
    path('mysite/about/', TemplateView.as_view(template_name="homepages/about.html"), name="about"),
    url(r'^mysite/pages/', include('homepages.urls')),
    # url(r'^mysite/books/', include('book.urls')),
    url(r'^mysite/lists/', include('lists.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/django/homepages/models.py
from django.db import models

# Create your models here.

services/django/homepages/views.py
from django.shortcuts import render

import datetime

# Create your views here.

def home_page(request):
    return render(request, 'homepages/index.html')

def date_time(request, offset=0):
    try:
        offset_ = int(offset)
    except ValueError:
        raise Http404()
    now = datetime.datetime.now() + datetime.timedelta(hours=offset_)
    return render(request, 'homepages/datetime.html', {"current_datetime": now})


def firstLoughe(request):
    return render(request, 'homepages/firstLoughe.html')


def newLounge(request):
    return render(request, 'homepages/newLounge.html')


def myFirstJavaScript(request):
    return render(request, 'homepages/myFirstJavaScript.html')


def json(request):
    return render(request, 'homepages/json/json.html')

services/django/templates/homepages/about.html
{% extends 'base.html' %}

{% block title %}Web Application{% endblock %}

{% block header_text %}
    <img src="/static/images/svg_logo.svg" alt="logo" width="100" height="100" />
    <h1 class="slogan">Welcome to Xu Zhiyong's Home Page!</h1>
{% endblock %}

{% block content %}
	<img src="/static/images/drinks.gif">
	<p>
		Join us any evening for refreshing  
		<a href={% url 'homepages:newLounge' %}>elixirs</a>,
		conversation and maybe a game or two of 
		<em>Dance Dance Revolution</em>.<br>
		Wireless access is always provided;
		<em>BYOWS</em> (Bring Your Own Web Server).
	</p>
	<h2>Directions</h2>
    <p>
      You'll find us right in the center of downtown Webville.   
      If you need help finding us, check out 
      our <a href={% url 'about' %}>detailed directions</a>.
      Come join us!
    </p>
	
{% endblock %}

services/django/templates/homepages/datetime.html
{% extends 'base.html' %}

{% block title %}Web Application{% endblock %}

{% block header_text %}
		<img src="/static/images/svg_logo.svg" alt="logo" width="100" height="100" />
		<h1 class="slogan">Welcome to Xu Zhiyong's Home Page!</h1>
{% endblock %}

{% block content %}
    <h2>
        Current local date/time is:
    </h2>
    <p class="text-center"> {{ current_datetime }}</p>
{% endblock %}

services/django/templates/homepages/firstLoughe.html
<html>
<head>
	<title>My first HTML&CSS web page</title>
	<link type="text/css" rel="stylesheet" href="/static/lounge.css">
    <link type="text/css" rel="stylesheet" href="/static/styledform.css">
</head>
<body>
	<h1>Welcome to George's Lounge</h1>
	<img src="/static/images/drinks.gif">
	<p>
		Join us any evening for refreshing  
		<a href={% url 'homepages:newLounge' %}>elixirs</a>,
		conversation and maybe a game or two of 
		<em>Dance Dance Revolution</em>.<br>
		Wireless access is always provided;
		<em>BYOWS</em> (Bring Your Own Web Server).
	</p>
	<h2>Directions</h2>
    <p>
      You'll find us right in the center of downtown Webville.   
      If you need help finding us, check out 
      our <a href={% url 'about' %}>detailed directions</a>.
      Come join us!
    </p>
    <hr>
    <h1>The Starbuzz Bean Machine</h1>
    <h2>Fill out the form below and click "Order now" to order</h2>
    <form action="http://starbuzzcoffee.com/processorder.php" method="post">
        <div class="tableRow">
            <p>
                <label for="choice"> Choose your beans:</label>
            </p>
            <p>
                <select name="beans" id="choice">
                    <option value="House Blend">House Blend</option>
                    <option value="Bolivia">Bolivia</option>
                    <option value="Organic Guatemala">Organic Guatemala</option>
                    <option value="Kenya">Kenya</option>
                </select>
            </p>
        </div>
        <div class="tableRow">
            <p>
                <fieldset>
                    <legend>Type</legend>
                        <input type="radio" id="whole_beantype" name="beantype" value="whole" >
                        <label for="whole_beantype">Whole bean</label><br>
                        <input type="radio" id="ground_beantype" name="beantype" value="ground" checked>
                        <label for="ground_beantype"> Ground</label>
                </fieldset>
            </p>
            <p>
                <fieldset>
                    <legend>Extras</legend>
                        <input type="checkbox" name="extras[]" value="giftwrap">Gift wrap<br>
                        <input type="checkbox" name="extras[]" value="catalog" checked>Include catalog with order
                </fieldset>
            </p>
        </div>
        <div class="tableRow">
            <p>
                <label for="bags"> Number of bags: </label>
            </p>
            <p>
                <input type="number" id="bags" name="bags" min="1" max="10">
            </p>
         </div>
        <div class="tableRow">
            <p>
                <label for="date"> Must arrive by date:</label>
            </p>
            <p>
                <input type="date" id="date" name="date">
            </p>
        </div>
        <div class="tableRow">
            <p class="heading">  Ship to : </p>
            <p></p>
        </div>
        <div class="tableRow">
            <p> <label for="name"> Name: </label></p>
            <p> <input type="text" id="name" name="name"></p>
         </div>
        <div class="tableRow">
            <p><label for="address">Address:</label></p>
            <p><input type="text" id="address" name="address"></p>
        </div>
        <div class="tableRow">
            <p> <label for="city">City:</label></p>
            <p> <input type="text" id="city" name="city"></p>
        </div>
        <div class="tableRow">
            <p><label for="state">State:</label></p>
            <p><input type="text" id="state" name="state"></p>
        </div>
        <div class="tableRow">
            <p><label for="zip">Zip:</label></p>
            <p><input type="text" id="zip" name="zip"></p>
        </div>
        <div class="tableRow">
            <p><label for="phone">Phone:</label></p>
            <p><input type="tel" id="phone" name="phone"></p>
        </div>
        <div class="tableRow">
            <p> <label for="comments">Customer Comments:</label></p>
            <p>
                <textarea id="comments" name="comments" rows="5" cols="60"></textarea>
            </p>
        </div>
        <div class="tableRow">
            <p></p>
            <p> <input type="submit" value="Order now"> </p>
        </div>
    </form>
	
	<hr>
	<p>
		<a href={% url 'homepages:home' %}> Back homepage </a>
	</p>
	
	<footer>
      <small>
        &copy; 2017, Xu Zhiyong's Lounge<br>
        All trademarks and registered trademarks appearing on this site are
        the property of their respective owners.
      </small>
    </footer>
</body>
</html>

services/django/templates/homepages/index.html
{% extends 'base.html' %}

{% block title %}Web Application{% endblock %}

{% block header_text %}
		<img id="headerLogo" src="/static/images/svg_logo.svg" alt="logo" width="100" height="100" />
        <h1 class="slogan">Welcome to Xu Zhiyong's Home Page!</h1>
{% endblock %}

{% block content %}
        <p>
            <a href={% url 'homepages:newLounge' %} title="Link to another web-page">
                <img src="/static/images/jackal.jpg" alt="a picture of jackal" />
            </a>

            <em>
                Lao Tzu would have said, <br> <q> A journey of a thousand
                miles begins with the first step.</q>
            </em>
        </p>

        <h1>My address:</h1>
        <Address>
            No.3-1-2102, Jing Lan Ban Dao <br> No.488, HongJiXin Road <br>
            Jingjiang Distinct, Chengdu <br> Postnum: 610061
        </Address>

        <ol>
            <li>Charge Segway</li>
            <li>Pack for trip
                <ul>
                    <li>cell phone</li>
                    <li>iPod</li>
                </ul>
            </li>
            <li>Call mother</li>
        </ol>

        <p id='manpage'>Test:
            &#208;&epsilon;&tau;&#114;&ouml;&igrave;&tau;.</p>

        <p>How long a line can you draw with the typical pencil?</p>
        <p>
            <img src="http://www.headfirstlabs.com/trivia/pencil.gif"
                alt="pencil with the line" />
        </p>

        <hr>
        <h2>Links</h2>
        <p>
            <a href={% url 'homepages:datetime' %}       title="Link to current datetime web-page">Current Time</a> <br>
            <a href="../admin"                                       title="Link to website management page">Website Management</a> <br>
            <a href="../about"                                        title="Link to about page">About</a> <br>
            <a href={% url 'homepages:newLounge' %}   title="Link to HTML5&CSS web-page">HTML5&CSS Testing Page</a> <br>
    		<a href={% url 'homepages:firstLoughe' %}   title="Link to form testing web-page"> FORM Testing Page</a> <br>
            <a href={% url 'lists:home' %}                  title="Link to TDD testing web-page">Testing-Driven Design Home Page</a> <br>
    {#		<a href={% url 'homepages:myFirstJavaScript' %} title="Link to HTML5&JavaScript testing web-page">#}
    {#			HTML5&JavaScript Testing Page</a> <br> #}
    {#		<a href={% url 'homepages:json' %} title="Link to HTML5&JSON testing web-page">#}
    {#			HTML5&JSON Testing Page</a> <br> #}
    {#	  <a href={% url 'homepages:show_picture' %} title="Link to Bokeh webui"> Bokeh WebUI Testing Page</a> <br> #}
          <br>
            <a href="#top"> Back to top</a>
        </p>
{% endblock %}

services/django/templates/homepages/myFirstJavaScript.html
<!doctype html>
<html lang="en">
<head>
	<title>My first HTML&JavaScript web page</title>
	<meta charset="utf-8">
	<script src="/static/myJavaScript.js"></script>
	<script type="text/javascript" src="http://api.map.baidu.com/api?
	              key=&v=1.1&services=true"></script>
	<style>
		canvas {
			border: 1px solid black;
		}
		body {
			backgroud-color: #d2b48c;
			margin-left: 8%;
			margin-right: 8%;
			border: 1px dotted gray;
			padding: 10px 10px 10px 10px;
			font-family: "Courier New", Verdana, Helvetica, sans-serif;
		}
		p {
			color: maroon
		}
	</style>
</head>

<body>
	<h1>My blog</h1>
	<hr>
	<div id="entry1">
		<h2>Where am I:</h2>
		<p id="location">My location will go here.</p>
    <div style="width:697px;height:550px;border:#ccc solid 1px;" id="dituContent"></div>
	</div>

	<div id="entry2">
		<h2>My favorite songs</h2>
		<form>
			<input type="text" id="songTextInput" size="40" placeholder="Song name"> 
			<input type="button" id="addButton" value="Add Song">
		</form>
		<ul id="playlist"></ul>
	</div>

	<div id="entry3">
		<h2>Look What I Draw</h2>
		<canvas id="lookwhatIdrew" width="600" height="400">
     		<p>Hey, you need upgrade your browser for HTML5 supporting!</p>
     	</canvas>
		<form>
			<p>
				<label for="backgroundColor">Select background color:</label> 
				<select	id="backgroundColor">
					<option value="white" selected="selected">White</option>
					<option value="black">Black</option>
				</select>
			</p>
			<p>
				<label for="shape">Select shape:</label> 
				<select id="shape">
					<option value="none" selected="selected">Neither</option>
					<option value="circles">Circles</option>
					<option value="squares">Squares</option>
					<option value="triangles">Triangles</option>
					<option value="smileface">SmileFace</option>
				</select>
			</p>
			<p>
				<label for="foregroundColor">Select text color:</label>
				<select id="foregroundColor">
					<option value="black" selected="selected">Black</option>
					<option value="white">White</option>
				</select>
			</p>
			<p>
				<label for="tweets">Pick a tweet:</label> 
				<select id="tweets">
				</select>
			</p>
			<p>
				<input type="button" id="previewButton" value="Preview">
			</p>
		</form>
	</div>
	<hr>
	
	<div id="entry3">
		<h2>WebTV</h2>
		<video controls width="480" height="360" id="video">
		</video>
		<ul id="playlist"></ul>
	</div>
	<hr>
	<p>
		<a href={% url 'homepages:home' %}> Back homepage </a>
	</p>
</body>
</html>

services/django/templates/homepages/newLounge.html
<!DOCTYPE html>
<html> 
  <head>
    <meta charset="utf-8">
    <title>New Lounge</title>
    <link type="text/css" rel="stylesheet" href="/static/lounge.css">
  </head>

  <body>
    <header class="top"><img src="/static/images/logo.gif" alt="Head First Lounge"></header>

    <aside id="elixirs" class="sidebar">
      <h2>Weekly Elixir Specials</h2>
      <p>
        <img src="/static/images/yellow.gif" alt="Lemon Breeze Elixir">
      </p>
      <h3>Lemon Breeze</h3>
      <p>
        The ultimate healthy drink, this elixir combines
        herbal botanicals, minerals, and vitamins with
        a twist of lemon into a smooth citrus wonder
        that will keep your immune system going all
        day and all night.
      </p>

      <p>
        <img src="/static/images/chai.gif" alt="Chai Chiller Elixir">
      </p>
      <h3>Chai Chiller</h3>
      <p>
        Not your traditional chai, this elixir mixes mat&eacute;
        with chai spices and adds an extra chocolate kick for
        a caffeinated taste sensation on ice.
      </p>

      <p>
        <img src="/static/images/black.gif" alt="Black Brain Brew Elixir">
      </p>
      <h3>Black Brain Brew</h3>
      <p>
        Want to boost your memory?  Try our Black Brain Brew
        elixir, made with black oolong tea and just a touch
        of espresso.  Your brain will thank you for the boost.
      </p>

      <p>
        Join us any evening for these and all our 
        other wonderful 
        <a href="/static/beverages/elixir.html" 
           title="Head First Lounge Elixirs">elixirs</a>.
      </p>
    </aside>
    
	<hr>
    <section class="main">
        <h1>Welcome to the George's Lounge</h1>
        <p>
          The Head First Lounge is, no doubt, the biggest trendsetter in Webville.
          Stop in to sample the eclectic offering of elixirs, teas, and coffees,
          or, stay a bit longer and enjoy the multicultural culinary menu that
          combines a harmony of taste, texture, and color with the best in fresh
          and healthy ingredients.
        </p>

        <p>
          During your stay at the lounge, you'll enjoy a smooth mixture of
          ambient and mystic sounds, filling the lounge and adding an extra dimension
          to your dining experience. The decor surrounds you with the relaxing sentiments
          of sights from eras past. And, don't forget, the lounge offers free wireless
          access to the Internet, so bring your laptop.
        </p>

        <p id="guarantee">
          Our guarantee: at the lounge, we're committed to providing you,
          our guest, with an exceptional experience every time you visit.
          Whether you're just stopping by to check in on email over an
          elixir, or are here for an out-of-the-ordinary dinner, you'll
          find our knowledgeable service staff pay attention to every detail.
          If you're not fully satisfied, have a Blueberry Bliss Elixir on us.
        </p>

        <p>
          But that's not all; at night, join us in the backroom as our resident
          DJ spins a choice selection of trance and drum&amp;bass beats across
          our spacious tiki-themed dance floor. Or just hang out in one of our
          comfy white vinyl booths at the dance bar. You can have your elixirs
          delivered from the main lounge right to the dance floor. If you've
          had enough of the beat, just head back to the lounge area to relax.
          And, no matter where you find yourself in the lounge, you'll always be
          connected with our wireless Internet access.
        </p>

        <p>
          Now that you've experienced the lounge <em>virtually</em>, isn't
          it time to check us out <em>for real</em>? We're located right
          in the heart of Webville, and we've created some
          <a href="/static/about/directions.html"
             title="Detailed Directions to the Lounge">detailed directions</a>
          to get you here in record time. No reservations necessary;
          come and join us anytime.
        </p>

        <h2>What's playing at the Lounge</h2>
        <p>
          We're frequently asked about the music we play at the lounge, and no wonder,
          it's great stuff. Just for you, we keep a list here on the site, updated weekly.
          Enjoy.
        </p>
        <ul>
          <li><span class="cd">Buddha Bar</span>, <span class="artist">Claude Challe</span></li>
          <li><span class="cd">When It Falls</span>, <span class="artist">Zero 7</span></li>
          <li><span class="cd">Earth 7</span>, <span class="artist">L.T.J. Bukem</span></li>
          <li><span class="cd">Le Roi Est Mort, Vive Le Roi!</span>, <span class="artist">Enigma</span></li>
          <li><span class="cd">Music for Airports</span>, <span class="artist">Brian Eno</span></li>
        </ul>

        <hr>
        <p>
            <a href={% url 'homepages:home' %}> Back homepage </a>
        </p>
    </section>

    <footer>
      <small>
        &copy; 2017, Xu Zhiyong's Lounge<br>
        All trademarks and registered trademarks appearing on this site are
        the property of their respective owners.
      </small>
    </footer>
  </body>
</html>